config/routes.rb
Rails.application.routes.draw do
  get 'reservations/new'
  get 'cameras/index'
  get 'cameras/new'
  get 'cameras/create'
  get 'cameras/show'

  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :cameras, only: %i[index new create show edit update destroy] do
    resources :reservations, only: [:new, :create, :show]
  end

  resources :reservations, only: [:show]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/camera.rb
class Camera < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  validates :name, :price_per_day, presence: true
  validates :name, uniqueness: true
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  pg_search_scope :search_by_name_and_address_and_resolution,
                  against: %i[name address resolution],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :camera
<<<<<<< HEAD

  validates :start_date, :end_date, :num_cameras, presence: true
  validate :end_date_after_start_date

  private

 def end_date_after_start_date
  error.add(:end_date, "must be after the start date") if end_date < start_date
 end
=======
  validates :start_date, :end_date, presence: true

  before_save :set_total_price

  private

  def set_total_price
    self.total_price = (end_date - start_date).to_i * camera.price_per_day
  end
>>>>>>> 30a548b4fbe7a54df4b03ae4311a641f934f95f0
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :cameras
  has_many :reservations

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
  before_action :set_camera, only: [:show]
  def index
    if params[:query].present?
      #sql_subquery = "name @@ :query OR address @@ :query"
      #@cameras = Camera.where(sql_subquery,query: "%#{params[:query]}%")
      @cameras = Camera.search_by_name_and_address_and_resolution(params[:query])
      # Preventing SQL Injection and Database error for
      # unknown characters
    else
      @cameras = Camera.all
    end
    @markers = @cameras.geocoded.map do |camera|
      {
        lat: camera.latitude,
        lng: camera.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { camera: camera })
      }
    end
  end

  def new
    @camera = Camera.new
  end

  def create
    @camera = Camera.new(camera_params)
    @camera.user = current_user

    if @camera.save
      redirect_to cameras_path, notice: "Camera created!"
    else
      render :new, status: :unprocessable_entity
    end
  end


  def edit
    @camera = Camera.find(params[:id])
  end

  def update
    @camera = Camera.find(params[:id])

    if @camera.update(camera_params)
      redirect_to cameras_path, notice: "Camera updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @camera = Camera.find(params[:id])
    @camera = @camera.destroy
    redirect_to cameras_path, notice: "Camera deleted!"
  end

  def show
    @camera
  end


  private

  def set_camera
    @camera = Camera.find(params[:id])
  end

  def camera_params
    params.require(:camera).permit(:name, :optical_zoom, :address, :year, :resolution, :price_per_day)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[ show edit update destroy ]

  # GET /flats or /flats.json
  def index
    @flats = Flat.all
  end

  # GET /flats/1 or /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats or /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully created." }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1 or /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully updated." }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1 or /flats/1.json
  def destroy
    @flat.destroy!

    respond_to do |format|
      format.html { redirect_to flats_url, notice: "Flat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flat_params
      params.require(:flat).permit(:name, :address)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @cameras = Camera.all.sample(3)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_camera, only: %i[new create]
  def new
    @reservation = Reservation.new
    @markers = []
    set_marker
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.camera = @camera
    @reservation.user = current_user
    if @reservation.save
      redirect_to @reservation, notice: 'Reservation was successfully created.'
    else
      render :new, status: :unprocessable_entity, alert: 'Something went wrong'
    end
  end
  
  def show
    @reservation = Reservation.find(params[:id])
  end  

  private

  def set_camera
    @camera = Camera.find(params[:camera_id])
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end

  def set_marker
    coordinates = @camera.geocode
    return if coordinates.nil? || coordinates.empty?

    @markers.push(
      {
        lat: coordinates[0],
        lng: coordinates[1],
        info_window_html: render_to_string(partial: "cameras/info_window", locals: { camera: @camera })
      }
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cameras/_info_window.html.erb
<h3><%= camera.name %></h3>
<p class="fs-7"><%= camera.address %></p>
<div class="fs-6"><strong><%= camera.price_per_day %> €</strong> per day</div>

app/views/cameras/card_camera.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title"><%= link_to camera.name, camera_path(camera) %></h5>
    <p class="card-text">
      <strong>Optical Zoom:</strong> <%= camera.optical_zoom %><br>
      <strong>Address:</strong> <%= camera.address %><br>
      <strong>Year:</strong> <%= camera.year %><br>
      <strong>Resolution:</strong> <%= camera.resolution %><br>
      <strong>Price per day:</strong> <%= camera.price_per_day %>
    </p>
  </div>
</div>

app/views/cameras/edit.html.erb
<div class="container">
  <h1>Edit Camera</h1>
    <%= simple_form_for(@camera) do |f| %>
    <%= f.error_notification %>
    <%= f.input :name %>
    <%= f.input :optical_zoom %>
    <%= f.input :price_per_day %>
    <%= f.input :address %>
    <%= f.input :resolution %>
    <%= f.submit 'Update Camera', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/cameras/index.html.erb
<div class="container mt-5">
  <h1>All our Cameras</h1>
  <p>All <%= @cameras.size %> cameras</p>
  <div class="row">
    <div class="col-md-8">
      <div class="row gy-4">
        <% @cameras.each do |camera| %>

          <div class="col-md-4">
            <%= link_to camera_path(camera), class:"text-decoration-none" do %>
              <%= render "shared/card_camera", camera: camera %>

              <% if current_user == camera.user %>
                <%= link_to 'Edit', edit_camera_path(camera) %>
                <%= link_to 'Destroy', camera_path(camera), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>

              <% end %>
            <% end %>
          </div>

        <% end %>

      </div>
    </div>
    <div class="col-md-4">
      <div
        data-controller="map" class="vh-100 position-sticky top-0"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/cameras/new.html.erb
<div class="container">
  <h1>New Camera</h1>
  <p>Find me in app/views/cameras/new.html.erb</p>
  <br>
  <%= simple_form_for(@camera) do |f| %>
    <%= f.error_notification %>
    <%= f.input :name %>
    <%= f.input :optical_zoom %>
    <%= f.input :price_per_day %>
    <%= f.input :address %>
    <%= f.input :resolution %>
    <%= f.submit class: 'btn btn-primary'  %>
  <% end %>
</div>

app/views/cameras/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <div class="d-flex justify-content-between align-items-center">
        <h1><%= @camera.name %></h1>
        <%= link_to "Book", new_camera_reservation_path(@camera), class: "btn btn-success text-white" %>
      </div>
      <p>
        <strong>Optical Zoom:</strong>
        <%= @camera.optical_zoom %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @camera.address %>
      </p>

      <p>
        <strong>Resolution:</strong>
        <%= @camera.resolution %>
      </p>

      <p>
        <strong>Price per day:</strong>
        <%= @camera.price_per_day %>
      </p>
      <p>
        <strong>Owner:</strong>
        <%= @camera.user.first_name %>
      </p>

      <%= link_to 'Back to list', cameras_path %>
    </div>
  </div>
</div>

app/views/flats/_flat.html.erb
<div id="<%= dom_id flat %>">
  <p>
    <strong>Name:</strong>
    <%= flat.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= flat.address %>
  </p>

</div>

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Show this flat", @flat %> |
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Flats</h1>

<div id="flats">
  <% @flats.each do |flat| %>
    <%= render flat %>
    <p>
      <%= link_to "Show this flat", flat %>
    </p>
  <% end %>
</div>

<%= link_to "New flat", new_flat_path %>

app/views/flats/new.html.erb
<h1>New flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @flat %>

<div>
  <%= link_to "Edit this flat", edit_flat_path(@flat) %> |
  <%= link_to "Back to flats", flats_path %>

  <%= button_to "Destroy this flat", @flat, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>CameraRentals</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_importmap_tags %>

  </head>

  <body class="d-flex flex-column h-100">
    <%# <div class="main-container"> %>
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <%= yield  %>
      <%=  render "shared/footer" %>

    <%# </div> %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1551728715-941acefa8a3d?q=80&w=1925&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <div class="container">
    <h1>Welcome to Camera Rentals</h1>
    <p>Book highted rated camera for making your own movies</p>
    <%= link_to "Book now", cameras_path, class: "btn btn-flat" %>
  </div>
</div>



<div class="container">
  <h2 class="text-center my-5">Highlighted Products</h2>
  <div class="row">
    <% @cameras.each do |camera| %>
      <div class="col-md-4">
        <%= link_to camera_path(camera), class:"text-decoration-none" do %>
          <%= render "shared/card_camera", camera: camera %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1581591524425-c7e0978865fc);">
  <div class="container">
    </div>
  </div>


  <div class="container mt-5">
    <div class="row">
      <div class="col-8">
      <div class="d-flex justify-content-between">
          <div>
            <h1><%= @camera.name %></h1>

            <p class="camera-address-show"><%= @camera.address %></p>
          </div>
          <div><strong><%= @camera.user.first_name %></strong></div>
        </div>
        <div class="border-top border-3 pt-3 mt-4">
          <h3>Sepefication</h3>
          <table class="w-75 table spefication-table ">
            <tr>
              <td>Optical Zoom</td>
              <td><%= @camera.optical_zoom %></td>
            </tr>
            <tr>
              <td>Resolution</td>
              <td><%= @camera.resolution %></td>
            </tr>

          </table>

        </div>
      </div>
      <div class="col-4">
        <div class="bg-white rounded shadow p-3" data-controller="total" data-total-price-per-day-value="<%= @camera.price_per_day %>">
          <div class="d-flex mb-3 align-items-center">
            <span class="mr-3 fw-medium fs-4 ">€ <%= @camera.price_per_day %>&nbsp;</span>
            <span>  day</span>
          </div>

          <%= simple_form_for [@camera, @reservation],  data: { controller: 'datepicker' } do |f| %>
            <%= f.input :start_date, as: :string,  input_html: { data: { datepicker_target: "startDate", action: "input->total#calculateTotal" } }  %>

            <%= f.input :end_date, as: :string,  input_html: { data: { datepicker_target: "endDate", action: "input->total#calculateTotal"  }, id: 'end_time'} %>

            <%= f.button :submit,  class: "btn btn-primary" %>

          <% end %>
          <div class="d-flex justify-content-between border-top border-2 mt-4 pt-3">
                <div class="fw-semibold">Total</div>

                <div class="fw-semibold" data-total-target="total"   ></div>
          </div>
        </div>
      </div>
    </div>
    <div style="width: 100%; height: 600px;" class="mt-5"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

</div>

app/views/reservations/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h1 class="mb-3">Reservation Details</h1>

      <p>
        <strong>User:</strong>
        <%= @reservation.user.first_name %> <%= @reservation.user.last_name %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @reservation.camera.address %>
      </p>

      <p>
        <strong>Camera:</strong>
        <%= @reservation.camera.name %>
      </p>

      <p>
        <strong>Start Date:</strong>
        <%= @reservation.start_date %>
      </p>
      <p>
        <strong>Owner:</strong>
        <%= @reservation.camera.user.first_name %>
      </p>

      <p>
        <strong>End Date:</strong>
        <%= @reservation.end_date %>
      </p>

      <p>
        <strong>Total Price:</strong>
        <%= @reservation.total_price %>
      </p>

      <%= link_to 'Back to Cameras', cameras_path %>
    </div>
  </div>
</div>

app/views/shared/_card_camera.html.erb
<div class="card-camera" role="button">
  <img src="https://images.unsplash.com/photo-1502920917128-1aa500764cbd" />
  <div class="card-camera-infos text-dark">
    <div>
      <h2><%= camera.name %></h2>
    </div>
    <h2 class="card-camera-pricing">€<%= camera.price_per_day %></h2>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
      <div class="footer mt-auto">
        <div class="footer-links">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
        <div class="footer-copyright">
          This footer is made with <i class="fas fa-heart"></i> at Le Wagon
        </div>
      </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to  root_path, class: "navbar-brand" do %>
      <%= image_tag "camera-solid.svg", alt: "alttext", class: "logo" %> Camera Rentals
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <form class="d-flex my-2 my-lg-0" action="/cameras" >
              <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search" value="<%= params[:query] %>">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </li>
          <li class="nav-item active">
            <%= link_to "New Camera", new_camera_path, class: "btn btn-outline-primary mx-2" %>
          </li>

          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>